# Site settings
title: FFinchR's Personal
email: 
description: > # this means to ignore newlines until "baseurl:"
  FFFFFFFFFF
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  FFinchR

# Build settings
markdown: kramdown
permalink: pretty
